package: Fix perf build issues with linux-3.14
Currently perf throws compilation errors with linux-3.14
saying undefined reference to "dwfl_linux_kernel_find_elf"

These functions are part of libdwfl/linux-kernel-modules.c
and which is not enabled, so we enabled them in libdwfl.

perf is no more need headers from glibc, those are available
in uClibc/musl, hence dropped the glibc dependency.

Change-Id: Ied941fae26d6fd8ad8fcdb13a381766bbaf1eaad
Signed-off-by: Ram Chandra Jangir <rjangi@codeaurora.org>