samba server build depends on libuuid
02:41:03 In file included from ../lib/addns/dnsrecord.c:24:0:
02:41:03 ../lib/addns/dns.h:53:23: fatal error: uuid/uuid.h: No such
file or directory

Change-Id: I984fbc9f11dbdc79a9d466a5b995122341a11483
Signed-off-by: Matthew McClintock <mmcclint@codeaurora.org>