samba36:  samba server build depends on libuuid
02:41:03 In file included from ../lib/addns/dnsrecord.c:24:0:
02:41:03 ../lib/addns/dns.h:53:23: fatal error: uuid/uuid.h: No such
file or directory

Change-Id: I6e933eccc2623c62641d1c9ebc9aa91e95f1f7f6
Signed-off-by: Matthew McClintock <mmcclint@codeaurora.org>
Signed-off-by: Naresh Kumar Mehta <naresh@codeaurora.org>