package: Fix recursive dependency error in dnsmasq package
error: recursive dependency detected!
tmp/.config-package.in:129:    symbol PACKAGE_dnsmasq-full depends on PACKAGE_dnsmasq_full_dhcpv6
tmp/.config-package.in:151:    symbol PACKAGE_dnsmasq_full_dhcpv6 depends on PACKAGE_dnsmasq-full

Change-Id: I3acd150e9bf91b54cdbd4f9d7967201f46233f41
Signed-off-by: Ram Chandra Jangir <rjangi@codeaurora.org>