ipq40xx: Fix the errors on Ramdump TOT
when Ramdump parser TOT is reset to change id -
ad517ab5884135ec720a7b587af47eee7ea087ea
we will get the below error because of missing symbol "get_debug_flags"
Traceback (most recent call last):
  File "ramparse.py", line 130, in <module>
    for p in parser_util.get_parsers():
  File "C:\Users\c_nrameg\Desktop\TOP\linux-ramdump-parser-v2\parser_util.py", l
ine 107, in get_parsers
    __import__(modname)
  File "C:\Users\c_nrameg\Desktop\TOP\linux-ramdump-parser-v2\parsers\pageallocc
orruption.py", line 14, in <module>
    from mm import pfn_to_page, page_buddy , page_address ,get_debug_flags
ImportError: cannot import name get_debug_flags

Change-Id: I160e77ddb445c7d95ac61aa6e4a5772cfd18c517
Signed-off-by: Natesh babu <nrameg@codeaurora.org>